/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as eas from "./EAS";
export type { eas };
export type { GitcoinGrantsResolver } from "./GitcoinGrantsResolver";
